name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, nightly, 1.45.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy, rustfmt
      - run: make
      - run: cargo build --release
      - run: cargo test --release
        # Tests are broken on nightly due to https://github.com/rust-lang/rust/pull/83079.
        if: ${{ matrix.rust != 'nightly' }}
      - run: cargo fmt -- --check
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: cargo clippy
